export const initialProducts = [
  { produto: "ALUMAX 1,5L", litragem: "1,5 Litros" },
  { produto: "ALUMAX 20L", litragem: "20 Litros" },
  { produto: "ALUMAX 5L", litragem: "5 Litros" },
  { produto: "AROMINHA GEL CARRO NOVO 60G", litragem: "60g" },
  { produto: "AROMINHA GEL FRUTAL 60G", litragem: "60g" },
  { produto: "AROMINHA GEL UVA 60G", litragem: "60g" },
  { produto: "AROMINHA GEL VONIXX FRESH 60G", litragem: "60g" },
  { produto: "AROMINHA SPRAY BOMAR 60ML", litragem: "60ml" },
  { produto: "AROMINHA SPRAY CARRO NOVO 60ML", litragem: "60ml" },
  { produto: "AROMINHA SPRAY MORANGO 60ML", litragem: "60ml" },
  { produto: "AROMINHA SPRAY VONIXX FRESH 60ML", litragem: "60ml" },
  { produto: "BACTRAN 1,5L", litragem: "1,5 Litros" },
  { produto: "BACTRAN 3L", litragem: "3 Litros" },
  { produto: "BACTRAN 5L", litragem: "5 Litros" },
  { produto: "BLEND 100ML", litragem: "100ml" },
  { produto: "BLEND ALL IN ONE 240ML", litragem: "240ml" },
  { produto: "BLEND ALL IN ONE 500ML", litragem: "500ml" },
  { produto: "BLEND BLACK 100ML", litragem: "100ml" },
  { produto: "BLEND CLEANER BLACK WAX 500ML", litragem: "500ml" },
  { produto: "BLEND CLEANER WAX 500ML", litragem: "500ml" },
  { produto: "BLEND METAL POLISH 150G", litragem: "150g" },
  { produto: "BLEND SPRAY 500ML", litragem: "500ml" },
  { produto: "BLEND SPRAY BLACK 500ML", litragem: "500ml" },
  { produto: "BLOKER 240ML", litragem: "240ml" },
  { produto: "CARNAUBA EXPRESS 1,5L", litragem: "1,5 Litros" },
  { produto: "CARNAUBA HYBRID WAX 120ML", litragem: "120ml" },
  { produto: "CARNAUBA HYBRID WAX 240ML", litragem: "240ml" },
  { produto: "CARNAUBA PLUS 1,5L", litragem: "1,5 Litros" },
  { produto: "CARNAUBA PLUS 3L", litragem: "3 Litros" },
  { produto: "CARNAUBA PLUS 500ML", litragem: "500ml" },
  { produto: "CARNAUBA TOK FINAL 500ML", litragem: "500ml" },
  { produto: "CERA EXPRESS 500ML", litragem: "500ml" },
  { produto: "CHERRY WAX 1L", litragem: "1 Litro" },
  { produto: "CHERRY WAX 500ML", litragem: "500ml" },
  { produto: "CITRON SHAMPOO DESENGRAXANTE 1,5L", litragem: "1,5 Litros" },
  { produto: "DARKER 1,5L", litragem: "1,5 Litros" },
  { produto: "DARKER 500ML", litragem: "500ml" },
  { produto: "DARKER 5L", litragem: "5 Litros" },
  { produto: "DELET 1,5L", litragem: "1,5 Litros" },
  { produto: "DELET 500ML", litragem: "500ml" },
  { produto: "DELET 5L", litragem: "5 Litros" },
  { produto: "DESENGRAXANTE BIO 5L", litragem: "5 Litros" },
  { produto: "DRACCO 240ML", litragem: "240ml" },
  { produto: "DUOXY 240ML", litragem: "240ml" },
  { produto: "DURAX AEROSSOL 400ML", litragem: "400ml" },
  { produto: "ECOBLACK 1,5L", litragem: "1,5 Litros" },
  { produto: "ECOBLACK 20L", litragem: "20 Litros" },
  { produto: "ECOBLACK 5L", litragem: "5 Litros" },
  { produto: "ECOZUX 240ML", litragem: "240ml" },
  { produto: "EXTRACTUS 1,5L", litragem: "1,5 Litros" },
  { produto: "EXTRACTUS 3L", litragem: "3 Litros" },
  { produto: "EXTRACTUS 5L", litragem: "5 Litros" },
  { produto: "EXTRACTUS SENSITIVE 1,5L", litragem: "1,5 Litros" },
  { produto: "EXTRACTUS SENSITIVE 3L", litragem: "3 Litros" },
  { produto: "FLEXUS 500ML", litragem: "500ml" },
  { produto: "FLOW 1L", litragem: "1 Litro" },
  { produto: "FLOW 240ML", litragem: "240ml" },
  { produto: "FOCUS 240ML", litragem: "240ml" },
  { produto: "FOXY 1L", litragem: "1 Litro" },
  { produto: "FOXY 240ML", litragem: "240ml" },
  { produto: "GLADIUS 500ML", litragem: "500ml" },
  { produto: "GLAZOX 500ML ZACS", litragem: "500ml" },
  { produto: "GLAZY 1,5L", litragem: "1,5 Litros" },
  { produto: "GLAZY 500ML", litragem: "500ml" },
  { produto: "GLAZY 5L", litragem: "5 Litros" },
  { produto: "GLIZZ 500ML", litragem: "500ml" },
  { produto: "HIDRACOURO 500ML", litragem: "500ml" },
  { produto: "HIGICOURO 500ML", litragem: "500ml" },
  { produto: "HYDROX FAST 500ML", litragem: "500ml" },
  { produto: "HYDROX PRO 240ML", litragem: "240ml" },
  { produto: "HYDROX PRO 500ML", litragem: "500ml" },
  { produto: "IMPACT 1,5L", litragem: "1,5 Litros" },
  { produto: "IMPACT 3L", litragem: "3 Litros" },
  { produto: "IMPACT 5L", litragem: "5 Litros" },
  { produto: "IMPERMAX 1,5L", litragem: "1,5 Litros" },
  { produto: "INTENSE 1,5L", litragem: "1,5 Litros" },
  { produto: "INTENSE 240ML", litragem: "240ml" },
  { produto: "INTENSE 500ML", litragem: "500ml" },
  { produto: "IZER 1,5L", litragem: "1,5 Litros" },
  { produto: "IZER 1000L", litragem: "1000 Litros" },
  { produto: "IZER 3L", litragem: "3 Litros" },
  { produto: "IZER 500ML", litragem: "500ml" },
  { produto: "KAZAN RED 240ML", litragem: "240ml" },
  { produto: "KOUREX 240ML", litragem: "240ml" },
  { produto: "KOURUM 240ML", litragem: "240ml" },
  { produto: "LAVA AUTOS 1,5L", litragem: "1,5 Litros" },
  { produto: "LAVA AUTOS 20L", litragem: "20 Litros" },
  { produto: "LAVA AUTOS 500ML", litragem: "500ml" },
  { produto: "LAVA AUTOS 5L", litragem: "5 Litros" },
  { produto: "LIMPA ESTOFADOS 1,5L", litragem: "1,5 Litros" },
  { produto: "LIMPA ESTOFADOS 5L", litragem: "5 Litros" },
  { produto: "LIMPA VIDROS 1,5L", litragem: "1,5 Litros" },
  { produto: "LIMPA VIDROS 500ML", litragem: "500ml" },
  { produto: "LIMPA VIDROS 5L", litragem: "5 Litros" },
  { produto: "LIMPA VIDROS PRO 1,5L", litragem: "1,5 Litros" },
  { produto: "LIMPADOR MULTIACAO 1,5L", litragem: "1,5 Litros" },
  { produto: "LIMPADOR MULTIACAO 500ML", litragem: "500ml" },
  { produto: "LIMPADOR MULTIACAO 5L", litragem: "5 Litros" },
  { produto: "MASSA DE POLIR 1,8KG", litragem: "1,8Kg" },
  { produto: "MASSA DE POLIR 590G", litragem: "590g" },
  { produto: "METALUX 100G", litragem: "100g" },
  { produto: "MICROLAV 1,5L", litragem: "1,5 Litros" },
  { produto: "MICROLAV 500ML", litragem: "500ml" },
  { produto: "MITTUS 500ML - ZACS", litragem: "500ml" },
  { produto: "MOKER 1L", litragem: "1 Litro" },
  { produto: "MOKER 240ML", litragem: "240ml" },
  { produto: "MOTO-V LAVA MOTOS 1,5L", litragem: "1,5 Litros" },
  { produto: "MOTO-V LAVA MOTOS 500ML", litragem: "500ml" },
  { produto: "MOTUX 1L", litragem: "1 Litro" },
  { produto: "MOTUX 240ML", litragem: "240ml" },
  { produto: "NATIVE 100ML", litragem: "100ml" },
  { produto: "NATIVE BLACK 100ML", litragem: "100ml" },
  { produto: "NATIVE CLEANER WAX 500ML", litragem: "500ml" },
  { produto: "NATIVE SPRAY WAX 500ML", litragem: "500ml" },
  { produto: "NUBER 240ML", litragem: "240ml" },
  { produto: "OPTY 240ML", litragem: "240ml" },
  { produto: "PASTA MULTIACAO 500G", litragem: "500g" },
  { produto: "PNEU PRETINHO 1,5L", litragem: "1,5 Litros" },
  { produto: "PNEU PRETINHO 20L", litragem: "20 Litros" },
  { produto: "PNEU PRETINHO 500ML", litragem: "500ml" },
  { produto: "PNEU PRETINHO 5L", litragem: "5 Litros" },
  { produto: "PRIZM 1,5L", litragem: "1,5 Litros" },
  { produto: "PRIZM 500ML", litragem: "500ml" },
  { produto: "PULVIFLEX 1,5L", litragem: "1,5 Litros" },
  { produto: "PULVIFLEX 20L", litragem: "20 Litros" },
  { produto: "PULVIFLEX 5L", litragem: "5 Litros" },
  { produto: "QUANT - PULVERIZADOR DE DILUIÇÃO 500ML", litragem: "500ml" },
  { produto: "REFLECT 500ML", litragem: "500ml" },
  { produto: "REJUVEX 400G", litragem: "400g" },
  { produto: "REJUVEX BLACK 400G", litragem: "400g" },
  { produto: "REMOVEDOR DE CIMENTOS 5L", litragem: "5 Litros" },
  { produto: "REMOVEX 1,5L", litragem: "1,5 Litros" },
  { produto: "REMOVEX 20L", litragem: "20 Litros" },
  { produto: "REMOVEX 5L", litragem: "5 Litros" },
  { produto: "RENOVA PLASTICOS 1,5L", litragem: "1,5 Litros" },
  { produto: "RENOVA PLASTICOS 200G", litragem: "200g" },
  { produto: "RENOVA PLASTICOS 3L", litragem: "3 Litros" },
  { produto: "RENOVA PLÁTICOS 500ML", litragem: "500ml" },
  { produto: "RESTAURAX 1,5L", litragem: "1,5 Litros" },
  { produto: "RESTAURAX 240ML", litragem: "240ml" },
  { produto: "RESTAURAX 500ML", litragem: "500ml" },
  { produto: "RESTAURAX AEROSSOL 400ML", litragem: "400ml" },
  { produto: "REVELAX 3L", litragem: "3 Litros" },
  { produto: "REVELAX 500ML", litragem: "500ml" },
  { produto: "REVELAX 5L", litragem: "5 Litros" },
  { produto: "REVOX 1,5L", litragem: "1,5 Litros" },
  { produto: "REVOX 500ML", litragem: "500ml" },
  { produto: "REZET 500ML ZACS", litragem: "500ml" },
  { produto: "SANITIZANTE BOM AR 1,5L", litragem: "1,5 Litros" },
  { produto: "SANITIZANTE BOM AR 5L", litragem: "5 Litros" },
  { produto: "SANITIZANTE CARRO NOVO 1,5L", litragem: "1,5 Litros" },
  { produto: "SANITIZANTE CARRO NOVO 5L", litragem: "5 Litros" },
  { produto: "SANITIZANTE FINALIZADOR 1,5L", litragem: "1,5 Litros" },
  { produto: "SANITIZANTE FINALIZADOR 3L", litragem: "3 Litros" },
  { produto: "SANITIZANTE FINALIZADOR 5L", litragem: "5 Litros" },
  { produto: "SANITIZANTE FRUTAL 1,5L", litragem: "1,5 Litros" },
  { produto: "SANITIZANTE FRUTAL 5L", litragem: "5 Litros" },
  { produto: "SANITIZANTE VINTEX FRESH 1,5L", litragem: "1,5 Litros" },
  { produto: "SANITIZANTE VINTEX FRESH 5L", litragem: "5 Litros" },
  { produto: "SHINY 1,5L", litragem: "1,5 Litros" },
  { produto: "SHINY 240ML", litragem: "240ml" },
  { produto: "SHINY 500ML", litragem: "500ml" },
  { produto: "SILICONE LIQUIDO 1,5L", litragem: "1,5 Litros" },
  { produto: "SILVERT 240ML", litragem: "240ml" },
  { produto: "SINERGY PAINT 500ML", litragem: "500ml" },
  { produto: "SINERGY PLASTIC 500ML", litragem: "500ml" },
  { produto: "SINERGY WHEEL 500ML", litragem: "500ml" },
  { produto: "SINTRA FAST 500ML", litragem: "500ml" },
  { produto: "SINTRA PRO 1,5L", litragem: "1,5 Litros" },
  { produto: "SINTRA PRO 3L", litragem: "3 Litros" },
  { produto: "SINTRA PRO 5L", litragem: "5 Litros" },
  { produto: "SIO2-PRO 500ML", litragem: "500ml" },
  { produto: "SOULT FAST - LIMPADOR DE BOINAS 500ML", litragem: "500ml" },
  { produto: "SOULT PRO - LIMPADOR DE BOINAS 3L", litragem: "3 Litros" },
  { produto: "SPELL 500ML", litragem: "500ml" },
  { produto: "STRIKE 1,5L", litragem: "1,5 Litros" },
  { produto: "STRIKE 500ML", litragem: "500ml" },
  { produto: "SUPER CERA 1,5L", litragem: "1,5 Litros" },
  { produto: "SUPER CERA 200G", litragem: "200g" },
  { produto: "SUPER CERA 3L", litragem: "3 Litros" },
  { produto: "SUPER CERA 500ML", litragem: "500ml" },
  { produto: "TARGUS 500ML ZACS", litragem: "500ml" },
  { produto: "TRICOVER 20ML", litragem: "20ml" },
  { produto: "TYRANT 240ML", litragem: "240ml" },
  { produto: "V-CUT POLIDOR CORTE PREMIUM 500ML", litragem: "500ml" },
  { produto: "V-ECO 1,5L", litragem: "1,5 Litros" },
  { produto: "V-ECO FAST 500ML", litragem: "500ml" },
  { produto: "V-ENERGY 50ML", litragem: "50ml" },
  { produto: "V-FINISH POLIDOR LUSTRO PREMIUM 500ML", litragem: "500ml" },
  { produto: "V-FLOC 1,5L", litragem: "1,5 Litros" },
  { produto: "V-FLOC 3L", litragem: "3 Litros" },
  { produto: "V-FLOC 500ML", litragem: "500ml" },
  { produto: "V-FLOC 5L", litragem: "5 Litros" },
  { produto: "V-LEATHER PRO 50ML", litragem: "50ml" },
  { produto: "V-LIGHT 20ML", litragem: "20ml" },
  { produto: "V-LIGHT PRO 50ML", litragem: "50ml" },
  { produto: "V-LUB 3L", litragem: "3 Litros" },
  { produto: "V-LUB 500ML", litragem: "500ml" },
  { produto: "V-MOL 1,5L", litragem: "1,5 Litros" },
  { produto: "V-MOL 500ML", litragem: "500ml" },
  { produto: "V-MOL 5L", litragem: "5 Litros" },
  { produto: "V-PAINT 20ML", litragem: "20ml" },
  { produto: "V-PAINT PRO 50ML", litragem: "50ml" },
  { produto: "V-PLASTIC 20ML", litragem: "20ml" },
  { produto: "V-PLASTIC PRO 50ML", litragem: "50ml" },
  { produto: "V-POLISH POLIDOR REFINO PREMIUM 500ML", litragem: "500ml" },
  { produto: "V10-CORTE VERNIZ ASIÁTICO 500ML", litragem: "500ml" },
  { produto: "V20 - REFINO VERNIZ ASIÁTICO 500ML", litragem: "500ml" },
  { produto: "V30-LUSTRO VERNIZ ASIÁTICO 500ML", litragem: "500ml" },
  { produto: "V40 4EM1 500ML", litragem: "500ml" },
  { produto: "V80 SELANTE SINTETICO 500ML", litragem: "500ml" },
  { produto: "VASELINA LIQUIDA 5L", litragem: "5 Litros" },
  { produto: "VERNIZ DE MOTOR 1,5L", litragem: "1,5 Litros" },
  { produto: "VERNIZ DE MOTOR AEROSSOL 400ML", litragem: "400ml" },
  { produto: "VEROM 1,5L", litragem: "1,5 Litros" },
  { produto: "VERSE 1,5L", litragem: "1,5 Litros" },
  { produto: "VERSE 500ML", litragem: "500ml" },
  { produto: "VERTEX 1,5L", litragem: "1,5 Litros" },
  { produto: "VERTEX 500ML", litragem: "500ml" },
  { produto: "VERTEX 5L", litragem: "5 Litros" },
  { produto: "VEXUS 1,5L", litragem: "1,5 Litros" },
  { produto: "VEXUS 500ML", litragem: "500ml" },
  { produto: "VEXUS 5L", litragem: "5 Litros" },
  { produto: "Z CUT FAST 1L - ZACS", litragem: "1 Litro" },
  { produto: "ZUCS 500ML", litragem: "500ml" },
  { produto: "ΚΑΖΑΝ BLUE 240ML", litragem: "240ml" },
  { produto: "V-FLOC 240ML", litragem: "240ml" },
  { produto: "ACIDUS PRO 1,5L", litragem: "1,5 Litros" },
  { produto: "HYDROX WASH 500ML", litragem: "500ml" },
  { produto: "HYDROX WASH 240ML", litragem: "240ml" },
  { produto: "BARRA DESCONTAMINANTE 50G", litragem: "50g" },
  { produto: "MAKKER 2.0 500ML", litragem: "500ml" },
  { produto: "MINUX 500ML", litragem: "500ml" },
  { produto: "GLAZY ANTI-FOG 500ML", litragem: "500ml" },
  { produto: "REXER 500ML", litragem: "500ml" },
  { produto: "MINUX 1L", litragem: "1 Litro" },
  { produto: "EVOPLASTIC BLACK 400G", litragem: "400g" },
  { produto: "SEM PROGRAMAÇÃO", litragem: "" },
  { produto: "CITRUS 500ML", litragem: "500ml" },
  { produto: "TRYON 240ML", litragem: "240ml" },
  { produto: "REXER 240ML", litragem: "240ml" },
  { produto: "BLEND PASTE WAX 100ML", litragem: "100ml" },
  { produto: "KAZAN BLUE 240ML", litragem: "240ml" },
  { produto: "GLICOSE IBC", litragem: "IBC" },
  { produto: "DARKER IBC", litragem: "IBC" },
  { produto: "SUPER BRILHO 500ML", litragem: "500ml" },
  { produto: "ACIDUS FAST 500ML", litragem: "500ml" },
  { produto: "EVO200 POLIDOR DE CORTE 500ML", litragem: "500ml" },
  { produto: "CERAMIC PASTE WAX 200G", litragem: "200g" },
  { produto: "EVO300 500ML", litragem: "500ml" },
  { produto: "ZYON 500ML", litragem: "500ml" },
  { produto: "SEM INFORMAÇÃO", litragem: "" },
  { produto: "MITTUS 1L - ZACS", litragem: "1 Litro" },
  { produto: "LUSTER CERA CLEANER SPRAY 500ML", litragem: "500ml" },
  { produto: "ENVASADORA INOPERANTE", litragem: "ENVASADORA INOPERANTE" },
  { produto: "MITTUS 200ML - ZACS", litragem: "200ml" },
  { produto: "LAURIL IBC", litragem: "IBC" },
  { produto: "Indisponibilidade de maquinário", litragem: "" },
  { produto: "SINTRA MULTI PY 500ML", litragem: "500ml" },
  { produto: "MANUTENÇÃO PREVENTIVA", litragem: "" },
  { produto: "REFLECT 200ML", litragem: "200ml" },
  { produto: "TRYON 500ML", litragem: "500ml" },
  { produto: "TRYON 1,5L", litragem: "1,5 Litros" },
  { produto: "CHERRY WAX 200ML", litragem: "200ml" },
  { produto: "MAKKER 2.0 240ML", litragem: "240ml" },
  { produto: "ACIDUS PRO 5L", litragem: "5 Litros" },
  { produto: "PI 0004 IBC", litragem: "IBC" }
];
